import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import md5 from "npm:js-md5@0.8.3";

const site=Deno.env.get("SITE_URL")||"https://www.ijlanga.co.za";
const supabaseUrl=Deno.env.get("SUPABASE_URL")!;
const cors={"Access-Control-Allow-Origin":site,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const enc=(v:string)=>encodeURIComponent(String(v).trim()).replace(/%20/g,"+");
const signature=(data:Record<string,string>,passphrase?:string)=>{const parts=Object.entries(data).filter(([,v])=>v!=="").map(([k,v])=>`${k}=${enc(v)}`);if(passphrase)parts.push(`passphrase=${enc(passphrase)}`);return md5(parts.join("&"));};
const splitName=(name:string)=>{const p=String(name||"Customer").trim().split(/\s+/);return{first:p.shift()||"Customer",last:p.join(" ")||""}};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{
 const client=createClient(supabaseUrl,Deno.env.get("SUPABASE_ANON_KEY")||"",{global:{headers:{Authorization:req.headers.get("Authorization")||""}}});const{data:{user}}=await client.auth.getUser();if(!user)return json({error:"Authentication required"},401);
 const{data:profile}=await client.from("profiles").select("role").eq("id",user.id).maybeSingle();const isAdmin=profile?.role==="admin";
 const b=await req.json(),orderId=String(b.order_id||""),invoiceId=b.invoice_id?String(b.invoice_id):null;if(!orderId)return json({error:"order_id is required"},400);
 let query=client.from("orders").select("id,order_number,total,payment_status,customer_id,customer_name,customer_email,customers!inner(auth_user_id,contact_name,email,phone)").eq("id",orderId);if(!isAdmin)query=query.eq("customers.auth_user_id",user.id);const{data:order,error:oe}=await query.maybeSingle();if(oe||!order)return json({error:"Order not found or access denied"},404);
 let amount=Math.round(Number(order.total||0)*1.15*100)/100,target:any=null;if(invoiceId){const{data:i,error:ie}=await client.from("invoices").select("id,invoice_number,total,amount_paid,balance_due,status,customer_id,order_id").eq("id",invoiceId).eq("order_id",order.id).maybeSingle();if(ie||!i)return json({error:"Invoice not found or access denied"},404);if(Number(i.balance_due||0)<=0)return json({error:"Invoice is already paid"},409);amount=Math.round(Number(i.balance_due)*100)/100;target=i}else if(order.payment_status==="paid")return json({error:"Order is already paid"},409);if(amount<=0)return json({error:"Nothing is due for this payment"},409);
 const merchantId=Deno.env.get("PAYFAST_MERCHANT_ID")?.trim(),merchantKey=Deno.env.get("PAYFAST_MERCHANT_KEY")?.trim(),passphrase=Deno.env.get("PAYFAST_PASSPHRASE")?.trim()||"",mode=(Deno.env.get("PAYFAST_MODE")||"sandbox").toLowerCase();if(!merchantId||!merchantKey)return json({error:"Payfast credentials are not configured yet"},503);
 const paymentRef=`PF-${order.order_number}-${Date.now()}`,customer=Array.isArray(order.customers)?order.customers[0]:order.customers,name=splitName(customer?.contact_name||order.customer_name||"Customer");
 const data:Record<string,string>={merchant_id:merchantId,merchant_key:merchantKey,return_url:`${site}/?payment=success&provider=payfast&order=${encodeURIComponent(order.order_number)}`,cancel_url:`${site}/?payment=cancelled&provider=payfast&order=${encodeURIComponent(order.order_number)}`,notify_url:`${supabaseUrl}/functions/v1/payfast-itn`,name_first:name.first,name_last:name.last,email_address:order.customer_email||customer?.email||user.email||"",m_payment_id:paymentRef,amount:amount.toFixed(2),item_name:target?target.invoice_number:order.order_number,item_description:target?`IJ Langa Consulting invoice ${target.invoice_number}`:`IJ Langa Consulting order ${order.order_number}`,custom_str1:order.id,custom_str2:target?.id||"",custom_str3:isAdmin?"admin":user.id};data.signature=signature(data,passphrase);
 const{error:pe}=await client.from("payments").insert({order_id:order.id,provider:"payfast",reference:paymentRef,amount,status:"pending",metadata:{mode,invoice_id:target?.id||null,merchant_id:merchantId,item_name:data.item_name,created_by:user.id}});if(pe)return json({error:pe.message},500);
 await client.from("orders").update({payment_status:"pending",payment_reference:paymentRef,updated_at:new Date().toISOString()}).eq("id",order.id);
 const host=mode==="live"?"www.payfast.co.za":"sandbox.payfast.co.za";return json({ok:true,payment_url:`https://${host}/eng/process`,fields:data,amount,order_number:order.order_number,payment_reference:paymentRef,provider:"payfast",invoice_number:target?.invoice_number||null});
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:"Could not start Payfast payment"},400)}});
