import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const site = Deno.env.get("SITE_URL") || "https://www.ijlanga.co.za";
const cors = {"Access-Control-Allow-Origin":site,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const esc=(s:string)=>s.replace(/[\\\"']/g,"\\$&").replace(/\u0000/g,"\\0");
async function sign(s:string,k:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(k.trim()),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const b=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{
 const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")||"",{global:{headers:{Authorization:req.headers.get("Authorization")||""}}});const{data:{user}}=await sb.auth.getUser();if(!user)return json({error:"Authentication required"},401);
 const b=await req.json(),orderId=String(b.order_id||""),invoiceId=b.invoice_id?String(b.invoice_id):null;if(!orderId)return json({error:"order_id is required"},400);
 const{data:o,error:oe}=await sb.from("orders").select("id,order_number,total,payment_status,customer_id,customer_name,customer_email,customers!inner(auth_user_id,contact_name,email)").eq("id",orderId).eq("customers.auth_user_id",user.id).maybeSingle();if(oe||!o)return json({error:"Order not found or access denied"},404);
 let amount=Math.round(Number(o.total||0)*1.15*100)/100,target:any=null;if(invoiceId){const{data:i,error:ie}=await sb.from("invoices").select("id,invoice_number,total,amount_paid,balance_due,status,customer_id,order_id").eq("id",invoiceId).eq("order_id",o.id).eq("customer_id",o.customer_id).maybeSingle();if(ie||!i)return json({error:"Invoice not found or access denied"},404);if(Number(i.balance_due||0)<=0)return json({error:"Invoice is already paid"},409);amount=Math.round(Number(i.balance_due)*100)/100;target=i}else if(o.payment_status==="paid")return json({error:"Order is already paid"},409);
 const app=Deno.env.get("IKHOKHA_APP_ID"),secret=Deno.env.get("IKHOKHA_APP_SECRET"),entity=Deno.env.get("IKHOKHA_ENTITY_ID")||app;if(!app||!secret||!entity)return json({error:"iKhokha credentials are not configured yet"},503);
 const endpoint="https://api.ikhokha.com/public-api/v1/api/payment",mode=Deno.env.get("IKHOKHA_MODE")||"live",ref=target?`${o.order_number}-${target.invoice_number}`:String(o.order_number),payload={entityID:entity,externalEntityID:String(o.customer_id),amount:Math.round(amount*100),currency:"ZAR",requesterUrl:site,mode,description:target?`IJ Langa Consulting invoice ${target.invoice_number}`:`IJ Langa Consulting order ${o.order_number}`,paymentReference:ref,externalTransactionID:ref,urls:{callbackUrl:`${Deno.env.get("SUPABASE_URL")}/functions/v1/ikhokha-webhook`,successPageUrl:`${site}/?payment=success&provider=ikhokha&order=${encodeURIComponent(o.order_number)}`,failurePageUrl:`${site}/?payment=failed&provider=ikhokha&order=${encodeURIComponent(o.order_number)}`,cancelUrl:`${site}/?payment=cancelled&provider=ikhokha&order=${encodeURIComponent(o.order_number)}`}};
 const body=JSON.stringify(payload),sig=await sign(esc(new URL(endpoint).pathname+body),secret),res=await fetch(endpoint,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json","IK-APPID":app.trim(),"IK-SIGN":sig},body}),result=await res.json().catch(()=>({}));if(!res.ok||result.responseCode!=="00"||!result.paylinkUrl)return json({error:result.message||"Unable to create iK Pay payment link",response_code:result.responseCode||null},502);
 const{error:pe}=await sb.from("payments").insert({order_id:o.id,provider:"ikhokha",reference:ref,amount,status:"pending",provider_transaction_id:result.paylinkID??null,metadata:{...result,invoice_id:target?.id||null,amountInclVat:amount,vatRate:15,paymentReference:ref}});if(pe)console.error(pe);await sb.from("orders").update({payment_status:"pending",payment_reference:ref,updated_at:new Date().toISOString()}).eq("id",o.id);
 return json({payment_url:result.paylinkUrl,paylink_id:result.paylinkID,order_number:o.order_number,amount,provider:"ikhokha",invoice_number:target?.invoice_number||null});
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:"Could not start payment."},400)}});
