import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,RefreshCw,ShieldCheck,UserCheck,UserX}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./admin-users.css';
const roles=['admin','employer','employee','reseller','client'];
function AdminUsers(){const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 async function loadSession(s){setSession(s);if(!s){setProfile(null);setLoading(false);return}const{data,error:e}=await supabase.from('profiles').select('id,email,full_name,role,is_active,job_title,department,created_at').eq('id',s.user.id).maybeSingle();if(e)setError(e.message);setProfile(data||null);if(data?.role==='admin')await loadUsers();setLoading(false)}
 async function loadUsers(){setError('');const{data,error:e}=await supabase.from('profiles').select('id,email,full_name,role,is_active,job_title,department,created_at').order('created_at',{ascending:false});if(e)setError(e.message);setUsers(data||[])}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>loadSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>loadSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function setAccess(u,role,is_active){setBusy(u.id);setError('');setNotice('');try{const{error:e}=await supabase.rpc('admin_set_profile_role',{p_user_id:u.id,p_role:role,p_is_active:is_active});if(e)throw e;setNotice(`${u.email||u.full_name||'User'} updated.`);await loadUsers()}catch(e){setError(e.message||'Could not update user.')}finally{setBusy('')}}
 if(loading)return <div className="users-loading">Loading user access…</div>;
 if(!session||!profile)return <main className="users-auth"><div className="users-card"><ShieldCheck size={30}/><h1>Sign in required</h1><p>Administrator authentication is required to manage user roles.</p><a href="/login.html">Go to sign in</a></div></main>;
 if(profile.role!=='admin')return <main className="users-auth"><div className="users-card"><UserX size={30}/><h1>Administrator access required</h1><p>This account cannot manage roles.</p><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></main>;
 return <main className="users-page"><header className="users-top"><div><span>IJ LANGA CONSULTING</span><h1>User access management</h1><p>Assign the dashboard role for each authenticated profile.</p></div><div><button onClick={loadUsers}><RefreshCw size={15}/> Refresh</button><a href="/admin.html"><ArrowLeft size={15}/> Admin dashboard</a></div></header>{notice&&<div className="users-notice">{notice}</div>}{error&&<div className="users-error">{error}</div>}<section className="users-card users-table-card"><div className="users-table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Job / Department</th><th>Access</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name||'Unnamed user'}</b><small>{u.email||'No email'}</small></td><td><select value={u.role} disabled={busy===u.id} onChange={e=>setAccess(u,e.target.value,u.is_active)}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></td><td><span className={u.is_active?'active':'inactive'}>{u.is_active?'Active':'Inactive'}</span></td><td>{u.job_title||'—'}{u.department?<small>{u.department}</small>:null}</td><td><button disabled={busy===u.id} onClick={()=>setAccess(u,u.role,!u.is_active)}>{u.is_active?<><UserX size={14}/> Disable</>:<><UserCheck size={14}/> Activate</>}</button></td></tr>)}</tbody></table></div></section><p className="users-note">Role changes take effect on the next dashboard access check. Passwords are handled by Supabase Auth and are never displayed here.</p></main>}
createRoot(document.getElementById('root')).render(<AdminUsers/>);
