import React,{useEffect,useState}from'react';import{ArrowLeft,RefreshCw,ShieldCheck,UserCheck,UserX,Send,Users}from'lucide-react';import{supabase}from'./lib/supabase';import'./admin-users.css';
const roles=['admin','employer','employee','reseller','client'];
function AdminUsers(){const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[users,setUsers]=useState([]),[employers,setEmployers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[form,setForm]=useState({email:'',full_name:'',role:'client',phone:'',job_title:'',department:'',organization_name:'',employer_id:''});
async function loadSession(s){setSession(s);if(!s){setProfile(null);setLoading(false);return}const{data:p,error:e}=await supabase.from('profiles').select('id,email,full_name,role,is_active').eq('id',s.user.id).maybeSingle();if(e)setError(e.message);setProfile(p||null);if(p?.role==='admin')await loadUsers();setLoading(false)}
async function loadUsers(){setError('');const{data,error:e}=await supabase.from('profiles').select('id,email,full_name,role,is_active,job_title,department,organization_name,employer_id,created_at').order('created_at',{ascending:false});if(e)setError(e.message);setUsers(data||[]);setEmployers((data||[]).filter(u=>u.role==='employer'&&u.is_active))}
useEffect(()=>{supabase.auth.getSession().then(({data})=>loadSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>loadSession(s));return()=>data.subscription.unsubscribe()},[]);
async function invite(e){e.preventDefault();setBusy('invite');setError('');setNotice('');try{const{data,error:e2}=await supabase.functions.invoke('admin-invite-user',{body:{...form,employer_id:form.role==='employee'?form.employer_id:null}});if(e2)throw e2;if(data?.error)throw new Error(data.error);setNotice(data.message||`Invitation sent to ${form.email}.`);setForm({email:'',full_name:'',role:'client',phone:'',job_title:'',department:'',organization_name:'',employer_id:''});await loadUsers()}catch(e){setError(e.message||'Could not send invitation.')}finally{setBusy('')}}
async function setAccess(u,role,is_active){setBusy(u.id);setError('');try{const{error:e}=await supabase.rpc('admin_set_profile_role',{p_user_id:u.id,p_role:role,p_is_active:is_active});if(e)throw e;setNotice(`${u.email||u.full_name||'User'} updated.`);await loadUsers()}catch(e){setError(e.message||'Could not update user.')}finally{setBusy('')}}
if(loading)return <div className="users-loading">Loading user access…</div>;
if(!session||!profile)return <main className="users-auth"><div className="users-card"><ShieldCheck size={30}/><h1>Sign in required</h1><p>Administrator authentication is required to manage users.</p><a href="/dashboard.html">Go to secure sign in</a></div></main>;
if(profile.role!=='admin')return <main className="users-auth"><div className="users-card"><UserX size={30}/><h1>Administrator access required</h1><p>This account cannot manage users.</p><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></main>;
return <main className="users-page"><header className="users-top"><div><span>IJ LANGA CONSULTING</span><h1>User access management</h1><p>Invite users, assign roles and control dashboard access.</p></div><div><button onClick={loadUsers}><RefreshCw size={15}/> Refresh</button><a href="/admin.html"><ArrowLeft size={15}/> Admin dashboard</a></div></header>{notice&&<div className="users-notice">{notice}</div>}{error&&<div className="users-error">{error}</div>}
<section className="users-card"><div className="users-head"><div><span>INVITE USER</span><h2>Create dashboard access</h2></div><Send size={20}/></div><form className="invite-grid" onSubmit={invite}><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label>Email address<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,employer_id:''})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Organisation<input value={form.organization_name} onChange={e=>setForm({...form,organization_name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Job title<input value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})}/></label><label>Department<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label>{form.role==='employee'&&<label>Employer<select value={form.employer_id} onChange={e=>setForm({...form,employer_id:e.target.value})} required><option value="">Select employer</option>{employers.map(e=><option key={e.id} value={e.id}>{e.full_name||e.email}</option>)}</select></label>}<div className="invite-actions"><button disabled={busy==='invite'}>{busy==='invite'?'Sending…':'Send invitation'}</button></div></form></section>
<section className="users-card users-table-card"><div className="users-head"><div><span>AUTHENTICATED USERS</span><h2><Users size={18}/> User directory</h2></div></div><div className="users-table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Organisation / Job</th><th>Access</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name||'Unnamed user'}</b><small>{u.email||'No email'}</small></td><td><select value={u.role} disabled={busy===u.id} onChange={e=>setAccess(u,e.target.value,u.is_active)}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td><span className={u.is_active?'active':'inactive'}>{u.is_active?'Active':'Inactive'}</span></td><td>{u.organization_name||'—'}<small>{u.job_title||'—'}{u.department?` · ${u.department}`:''}</small></td><td><button disabled={busy===u.id} onClick={()=>setAccess(u,u.role,!u.is_active)}>{u.is_active?<><UserX size={14}/> Disable</>:<><UserCheck size={14}/> Activate</>}</button></td></tr>)}</tbody></table></div></section><p className="users-note">Invitations are sent through Supabase Auth. Passwords are never displayed in the administration interface. Role changes are enforced by database policies and dashboard access checks.</p></main>}
createRoot(document.getElementById('root')).render(<AdminUsers/>);
