import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,BriefcaseBusiness,Building2,CheckCircle2,FileText,LogOut,Package,RefreshCw,ShieldCheck,Users,WalletCards}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./dashboard.css';

const roleMeta={
 employer:{label:'Employer Workspace',description:'Manage your business workspace and see the services connected to your account.',icon:Building2},
 employee:{label:'Employee Workspace',description:'Your personal work area for information and tasks assigned to your IJ Langa account.',icon:BriefcaseBusiness},
 reseller:{label:'Reseller Workspace',description:'Access the IJ Langa service catalogue and your reseller workspace.',icon:Package}
};
const money=n=>`R ${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2})}`;
const date=d=>d?new Date(d).toLocaleDateString('en-ZA',{dateStyle:'medium'}):'—';

function Dashboard(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[customer,setCustomer]=useState(null),[orders,setOrders]=useState([]),[invoices,setInvoices]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(s){setLoading(true);setError('');if(!s){setSession(null);setProfile(null);setLoading(false);return}setSession(s);const{data:p,error:pe}=await supabase.from('profiles').select('id,full_name,email,role,is_active,job_title,department').eq('id',s.user.id).maybeSingle();if(pe){setError(pe.message);setLoading(false);return}if(!p){setError('Your account has not been provisioned yet. Please contact IJ Langa Consulting.');setLoading(false);return}if(p.is_active===false){setError('Your account is inactive. Please contact IJ Langa Consulting.');setLoading(false);return}if(p.role==='admin'){window.location.replace('/admin.html');return}if(p.role==='client'){window.location.replace('/portal.html');return}setProfile(p);const[c,o,i,pr]=await Promise.all([supabase.from('customers').select('*').eq('auth_user_id',s.user.id).maybeSingle(),supabase.from('orders').select('id,order_number,status,payment_status,total,created_at').eq('customer_id',(await supabase.from('customers').select('id').eq('auth_user_id',s.user.id).maybeSingle()).data?.id||'00000000-0000-0000-0000-000000000000').order('created_at',{ascending:false}).limit(8),supabase.from('invoices').select('id,invoice_number,status,total,balance_due,issue_date').eq('customer_id',(await supabase.from('customers').select('id').eq('auth_user_id',s.user.id).maybeSingle()).data?.id||'00000000-0000-0000-0000-000000000000').order('created_at',{ascending:false}).limit(8),supabase.from('products').select('id,sku,name,category,price,price_label').eq('is_active',true).order('name').limit(12)]);setCustomer(c.data||null);setOrders(o.data||[]);setInvoices(i.data||[]);setProducts(pr.data||[]);setLoading(false)}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>load(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>load(s));return()=>data.subscription.unsubscribe()},[]);
 const role=profile?.role,meta=roleMeta[role],Icon=meta?.icon||ShieldCheck;const outstanding=useMemo(()=>invoices.reduce((s,i)=>s+Number(i.balance_due||0),0),[invoices]);
 if(loading)return <div className="role-loading">Loading your secure workspace…</div>;
 if(!session||error&&!profile)return <main className="role-auth"><div className="role-card"><ShieldCheck size={30}/><span className="role-eyebrow">SECURE WORKSPACE</span><h1>{error||'Please sign in'}</h1><p>{error?'Please contact IJ Langa Consulting if your account should have access.':'Your session is not active.'}</p><a className="role-button" href="/login.html">Go to sign in</a><a className="role-link" href="/">← Return to website</a></div></main>;
 return <main className="role-page"><header className="role-top"><div className="role-brand"><img src="/ijlanga-logo.svg" alt="IJ Langa Consulting logo"/><div><span className="role-eyebrow">IJ LANGA CONSULTING</span><strong>{meta.label}</strong></div></div><div className="role-actions"><button onClick={()=>load(session)}><RefreshCw size={15}/> Refresh</button><button onClick={()=>supabase.auth.signOut()}><LogOut size={15}/> Sign out</button></div></header><section className="role-hero"><div><div className="role-icon"><Icon size={23}/></div><span className="role-eyebrow">{profile.role.toUpperCase()}</span><h1>Welcome, {profile.full_name||profile.email?.split('@')[0]||'there'}.</h1><p>{meta.description}</p></div><div className="role-account"><span>Signed in as</span><b>{profile.email}</b>{profile.job_title&&<small>{profile.job_title}{profile.department?` · ${profile.department}`:''}</small>}</div></section>
 <section className="role-stats">{role==='employer'&&<><div><b>{orders.length}</b><span>Recent orders</span></div><div><b>{invoices.length}</b><span>Invoices</span></div><div><b>{money(outstanding)}</b><span>Balance due</span></div><div><b>{customer?'Active':'—'}</b><span>Business profile</span></div></>}{role==='employee'&&<><div><b>1</b><span>My profile</span></div><div><b>{profile.is_active?'Active':'Inactive'}</b><span>Account status</span></div><div><b>{profile.department||'—'}</b><span>Department</span></div><div><b>{profile.job_title||'—'}</b><span>Position</span></div></>}{role==='reseller'&&<><div><b>{products.length}</b><span>Services visible</span></div><div><b>{products.filter(p=>p.category).length}</b><span>Catalogue items</span></div><div><b>{profile.is_active?'Active':'Inactive'}</b><span>Account status</span></div><div><b>Online</b><span>Workspace</span></div></>}</section>
 <div className="role-grid"><section className="role-panel role-wide"><div className="role-panel-head"><div><span className="role-eyebrow">QUICK ACCESS</span><h2>Your workspace</h2></div></div><div className="role-modules">{role==='employer'&&<><a href="/portal.html"><FileText size={20}/><b>Billing & documents</b><span>Open the client portal for quotes, invoices, receipts and documents.</span><ArrowRight size={16}/></a><a href="mailto:info@ijlanga.co.za"><Users size={20}/><b>Business support</b><span>Contact IJ Langa Consulting about your business workspace.</span><ArrowRight size={16}/></a><a href="/"><Package size={20}/><b>Service catalogue</b><span>Browse available accounting, tax and compliance services.</span><ArrowRight size={16}/></a></>}{role==='employee'&&<><a href="#profile"><Users size={20}/><b>My profile</b><span>Review the account information currently held for your workspace.</span><ArrowRight size={16}/></a><a href="mailto:info@ijlanga.co.za"><FileText size={20}/><b>Contact support</b><span>Ask IJ Langa Consulting about documents, payroll or account questions.</span><ArrowRight size={16}/></a><a href="/"><Package size={20}/><b>Company website</b><span>Return to public information and service pages.</span><ArrowRight size={16}/></a></>}{role==='reseller'&&<><a href="/"><Package size={20}/><b>Service catalogue</b><span>Browse the current IJ Langa service catalogue and pricing.</span><ArrowRight size={16}/></a><a href="mailto:info@ijlanga.co.za"><WalletCards size={20}/><b>Reseller support</b><span>Contact IJ Langa Consulting about reseller account matters.</span><ArrowRight size={16}/></a><a href="/portal.html"><FileText size={20}/><b>Account portal</b><span>Open your client-facing billing area when your reseller account is also a customer.</span><ArrowRight size={16}/></a></>}</div></section>
 {role==='employer'&&<section className="role-panel"><div className="role-panel-head"><div><span className="role-eyebrow">SERVICE ACTIVITY</span><h2>Recent orders</h2></div></div>{!orders.length?<p className="role-muted">No orders are linked to this account yet.</p>:orders.map(o=><div className="role-row" key={o.id}><div><b>{o.order_number}</b><small>{date(o.created_at)}</small></div><span>{o.payment_status}</span></div>)}</section>}
 {role==='employer'&&<section className="role-panel"><div className="role-panel-head"><div><span className="role-eyebrow">FINANCE</span><h2>Invoices</h2></div></div>{!invoices.length?<p className="role-muted">No invoices are linked to this account yet.</p>:invoices.map(i=><div className="role-row" key={i.id}><div><b>{i.invoice_number}</b><small>{date(i.issue_date)}</small></div><span className={Number(i.balance_due)>0?'role-due':'role-paid'}>{Number(i.balance_due)>0?`Due ${money(i.balance_due)}`:'Paid'}</span></div>)}</section>}
 {role==='reseller'&&<section className="role-panel role-wide"><div className="role-panel-head"><div><span className="role-eyebrow">CATALOGUE</span><h2>Available services</h2></div></div><div className="role-product-grid">{products.map(p=><div className="role-product" key={p.id}><span>{p.category||'Service'}</span><b>{p.name}</b><small>{p.price_label||money(p.price)}</small></div>)}</div></section>}
 {role==='employee'&&<section className="role-panel role-wide" id="profile"><div className="role-panel-head"><div><span className="role-eyebrow">MY ACCOUNT</span><h2>Profile</h2></div></div><div className="role-profile-grid"><div><span>Name</span><b>{profile.full_name||'Not set'}</b></div><div><span>Email</span><b>{profile.email}</b></div><div><span>Job title</span><b>{profile.job_title||'Not set'}</b></div><div><span>Department</span><b>{profile.department||'Not set'}</b></div></div></section>}
 </div><footer className="role-footer"><CheckCircle2 size={16}/> Your access is controlled by your IJ Langa profile role and database permissions. <a href="/">Website</a></footer></main>;
}
createRoot(document.getElementById('root')).render(<Dashboard/>);
