import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Menu, X, ShoppingCart, ChevronDown, UserRound, Search, ArrowRight, ShieldCheck, BriefcaseBusiness, Calculator, FileText, Landmark, WalletCards, ClipboardList, Building2 } from 'lucide-react';
import './styles.css';

const services = [
  {
    title: 'Financial Statements: SMMEs', icon: FileText,
    columns: ['Revenue From', 'AFS', 'Management Accounts'],
    rows: [
      ['R - R 100 000','R 3 500','R 1 750'], ['R 100 000 - R 250 000','R 7 500','R 3 750'], ['R 250 000 - R 500 000','R 15 000','R 7 500'], ['R 500 000 - R 750 000','R 20 000','R 10 000'], ['R 750 000 - R 1 000 000','R 25 000','R 12 500'], ['R 1 000 000 - R 3 000 000','R 30 000','R 15 000'], ['R 3 000 000 - R 5 000 000','R 35 000','R 17 500'], ['R 5 000 000 - R 7 000 000','R 40 000','R 20 000'], ['R 7 000 000 - R 9 000 000','R 45 000','R 22 500'], ['R 9 000 000 - R 11 000 000','R 50 000','R 25 000'], ['R 11 000 000 - R 13 500 000','R 55 000','R 27 500'], ['R 13 500 000 - R 15 500 000','R 60 000','R 30 000'], ['R 15 500 000 - R 17 500 000','R 65 000','R 32 500'], ['R 17 500 000 - R 19 000 000','R 70 000','R 35 000'], ['R 20 000 000 +','R 75 000','R 37 500']
    ]
  },
  { title: 'Retainer Fees', icon: WalletCards, content: [
    ['R3 000 – R6 000/month','Accounting, Bookkeeping, Payroll, Tax and Compliance — R1–R5 million annual turnover','3–5 years retainer fees. Monthly rate varies with size and complexity.'],
    ['R6 000 – R12 000/month','Accounting, Bookkeeping, Payroll, Tax and Compliance — over R5 million annual turnover','Typically R6 000–R12 000/month, averaging around R9 000/month.'],
    ['R12 000 – R24 000/month','Accounting, Bookkeeping, Payroll, Tax and Compliance — over R10 million annual turnover','Typically R12 000–R24 000/month, averaging around R19 500/month.']
  ]},
  { title: 'Administration', icon: ClipboardList, rows: [['File - Admin Fee','R 480.00'],['Call out Fees Accommodation','R 6 500.00'],['Call-Out Fee around Polokwane (Depends on KM to Travel)','R 2 500.00'],['Call-Out Fee outside Polokwane (Depends on KM to Travel)','R 4 500.00']] },
  { title: 'Business Consultation', icon: BriefcaseBusiness, rows: [['Company Profile for Tenders','R 1 800.00'],['Entry level Business plan','R 4 500.00'],['Construction Business plan','R 5 500.00'],['Security Business plan (PSIRA approved)','R 5 500.00'],['Comprehensive Business plan','R 15 000.00'],['Specialised Business plan (Includes industry Research)','R 25 000.00'],['Lease agreements','R 1 800.00'],['Company Letterhead (Branding)','R 1 000.00'],['Professional Logo','R 2 000.00'],['Business Website Design from R4500','Price on request'],['Drafting of Engagement Letters','R 2 000.00'],['Tender Applications','R 5 000.00']] },
  { title: 'Secretarial Services', icon: Building2, rows: [['Company Registration (PTY) LTD) — Combo deal','R 3 500.00'],['Company registration (Only)','R 695.00'],['Co-operative Registration — Combo deal','R 4 500.00'],['Shelf Company','R 9 500.00'],['Security Company Registration (PSIRA Approved)','R 18 500.00'],['Co-Operative Registration (Only)','R 1 800.00'],['Non-Profit Company Registration (NPC)','R 1 650.00'],['Non-Profit Organisation Registration (NPO)','R 2 585.00'],['CSD Registration','R 1 265.00'],['CC to Pty Ltd Conversion','R 2 000.00'],['COIDA Registration','R 2 500.00'],['CIDB Registration','R 2 500.00'],['Filing of CIPC Annual Returns','R 520.00'],['Filing of Public Benefit Ownership with CIPC','R 1 050.00'],['Company Amendments — Registered Office Address','R 790.00'],['Company Amendments — Financial Year','R 700.00'],['Company Amendments — Company Contacts','R 700.00'],['Change company/CC Name','R 1 800.00'],['Add & Resign Directors/Members','R 1 700.00'],['Add Director/Member','R 1 000.00'],['Resign Director/Member','R 1 000.00'],['Change Directors/Members Contact Details','R 700.00'],['Accounting Officer/Secretary/Auditor Change','R 950.00'],['Special Resolution / MOI objective change','R 1 800.00'],['Defensive Name Reservation','R 800.00'],['BBBEE Certificate','R 528.00'],['SANAS Accredited BBBEE Certificate','R 1 056.00'],['Sworn Affidavit','R 1 056.00'],['Trademark Registration','R 9 500.00'],['Share Certificate For companies','R 528.00'],['Share Register','R 1 040.00'],['Shareholders Agreement','R 1 500.00'],['COIDA Letter of Good Standing — New','R 2 500.00'],['COIDA renewal — Letter of Good Standing','R 2 190.00'],['Company Deregistration','R 1 800.00']] },
  { title: 'Taxation Services', icon: Calculator, rows: [['Corporate/Company Income Tax Registration','R 1 950.00'],['VAT Registration','R 3 000.00'],['VAT Returns','R 1 950.00'],['Import and Export Licences Registration (Combo)','R 9 000.00'],['Import Licence Registration','R 5 500.00'],['Export Licence Registration','R 5 500.00'],['EMP201','R 1 500.00'],['EMP501 (Reconciliation)','R 5 500.00'],['EMP501 (Once-off Clients)','R 11 500.00'],['Tax Exemption Application','R 8 050.00'],['SDL Registration','R 1 980.00'],['Corporate Income Tax Return — Dormant','R 1 200.00'],['Corporate Income Tax Return — Operating','R 2 000.00'],['Provisional Tax (IRP6) — Dormant','R 960.00'],['Provisional Tax (IRP6) — Operating','R 1 350.00'],['Tax debt write off / compromise agreement','Annexure C'],['Income Tax Calculations','R 750.00'],['Capital Gains Tax Calculations (CGT)','R 1 100.00'],['Estate duty tax calculations','R 3 660.00'],['Dividends withholding tax calculations','R 3 660.00'],['Donations tax calculations','R 3 660.00'],['Trust Tax Registration','R 15 000.00'],['SARS payment arrangements','R 2 500.00'],['Customs Returns','R 2 200.00'],['Individual Income Tax Registration','R 1 210.00'],['Individual Income Tax Returns — IRP5 only','R 1 500.00'],['Individual Income Tax Returns — IRP + Rent','R 2 750.00'],['Individual Income Tax Returns — IRP + Travel Logbook','R 3 000.00'],['Corporate Updating of Representative','R 960.00'],['Maintaining SARS Details','R 1 100.00'],['Tax Clearance Certificate','R 520.00']] },
  { title: 'Payroll Administration', icon: Landmark, rows: [['PAYE and UIF Registration','R 3 000.00'],['UIF Registration','R 1 500.00'],['Payroll Run — Payslips (per payslip)','R 104.50'],['Employee Contract Preparation (per employee)','R 260.00'],['PAYE and UIF declarations and submissions','R 2 200.00'],['Letter of Good Standing from Labour','R 1 650.00']] },
  { title: 'Accounting Services', icon: ShieldCheck, rows: [['Financial Statement Preparation','Annexure B'],['Annual Financial Statements (Independent reviewed)','Annexure B'],['Bookkeeping — Monthly bank reconciliation & record keeping','R 2 500.00'],['Cash Flow Projections Report','R 2 200.00'],['Budget Preparations','R 2 000.00'],['Preparation of Management Accounts','Annexure B'],['Accounts Admin — Invoicing','R 1 375.00'],["Accountant’s Letter",'R 2 750.00']] }
];

function ServicePanel({ service, onClose }) {
  return <div className="service-panel">
    <div className="panel-head"><div><span className="eyebrow">IJ Langa Consulting</span><h2>{service.title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={20}/></button></div>
    {service.content && <div className="retainer-grid">{service.content.map((r,i)=><article className="info-card" key={i}><strong>{r[0]}</strong><h3>{r[1]}</h3><p>{r[2]}</p></article>)}</div>}
    {service.rows && <div className="table-wrap"><table><thead><tr>{(service.columns || ['Service','Price']).map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{service.rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className={j===r.length-1?'price':''}>{c}</td>)}</tr>)}</tbody></table></div>}
  </div>
}

function Header({ cartCount }) {
  const [open, setOpen] = useState(false); const [active, setActive] = useState(null); const [mobile, setMobile] = useState(false); const [login, setLogin] = useState(false);
  const choose = (s) => { setActive(s); setOpen(false); setMobile(false); };
  return <>
    <header className="site-header"><div className="topline"><span>Accounting • Taxation • Compliance • Business Consulting</span><span>South Africa</span></div><div className="nav-shell">
      <a className="brand" href="#home"><span className="brand-mark">IJ</span><span><b>IJ LANGA</b><small>CONSULTING</small></span></a>
      <button className="mobile-toggle" onClick={()=>setMobile(!mobile)} aria-label="Menu">{mobile?<X/>:<Menu/>}</button>
      <nav className={mobile?'main-nav mobile-open':'main-nav'}>
        <a href="#home" onClick={()=>setMobile(false)}>Home</a><a href="#about" onClick={()=>setMobile(false)}>About</a>
        <div className="nav-dropdown"><button onClick={()=>setOpen(!open)}>Services <ChevronDown size={16}/></button>{open && <div className="mega-menu">{services.map((s,i)=><button key={s.title} onClick={()=>choose(s)}><span className="service-icon"><s.icon size={17}/></span><span><b>{i+1}. {s.title}</b><small>View services & pricing</small></span><ArrowRight size={15}/></button>)}</div>}</div>
        <a href="#shop" onClick={()=>setMobile(false)}>Shop</a><a href="#contact" onClick={()=>setMobile(false)}>Contact Us</a>
        <button className="login-link" onClick={()=>setLogin(true)}><UserRound size={17}/> Login / Sign Up</button>
      </nav>
      <div className="nav-actions"><button className="search-btn" aria-label="Search"><Search size={19}/></button><button className="cart-btn" aria-label="Cart"><ShoppingCart size={20}/><span>{cartCount}</span></button><button className="portal-btn" onClick={()=>setLogin(true)}>Client Portal</button></div>
    </div></header>
    {active && <div className="overlay"><ServicePanel service={active} onClose={()=>setActive(null)}/></div>}
    {login && <div className="overlay"><div className="login-panel"><button className="icon-btn close-login" onClick={()=>setLogin(false)}><X/></button><span className="eyebrow">Secure access</span><h2>Login / Sign Up</h2><p>Choose your portal to continue.</p><div className="role-grid">{['Admin','Employer','Reseller','Employee','Client'].map(r=><button key={r} onClick={()=>setLogin(false)}><UserRound size={18}/><span>{r}</span><ArrowRight size={15}/></button>)}</div></div></div>}
  </>;
}

function Footer(){ return <footer id="contact"><div className="footer-main"><div className="footer-brand"><a className="brand light" href="#home"><span className="brand-mark">IJ</span><span><b>IJ LANGA</b><small>CONSULTING</small></span></a><p>Professional accounting, taxation, compliance and business consulting services for businesses and individuals.</p><a className="footer-cta" href="mailto:info@ijlanga.co.za">Contact Us <ArrowRight size={16}/></a></div><div><h4>Company</h4><a href="#home">Home</a><a href="#about">About</a><a href="#contact">Contact Us</a><a href="#shop">Shop</a></div><div><h4>Services</h4>{services.slice(0,5).map(s=><a href="#services" key={s.title}>{s.title}</a>)}</div><div><h4>Client Access</h4><a href="#login">Admin</a><a href="#login">Employer</a><a href="#login">Reseller</a><a href="#login">Employee</a><a href="#login">Client Portal</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} IJ Langa Consulting (Pty) Ltd. All rights reserved.</span><span>Privacy • Terms • POPIA</span></div></footer> }

function App(){ return <><Header cartCount={0}/><main id="home"><section className="hero"><div><span className="eyebrow">ACCOUNTING YOU CAN TRUST</span><h1>Business compliance, <em>without the complexity.</em></h1><p>Accounting, taxation, payroll, company secretarial and business consulting services designed to keep your business moving.</p><div className="hero-actions"><a className="primary" href="#shop">Explore Services <ArrowRight size={18}/></a><a className="secondary" href="#contact">Talk to us</a></div></div><div className="hero-card"><span>Professional services</span><strong>Built around your business.</strong><div className="hero-stat"><b>01</b><span>Tax & Compliance</span></div><div className="hero-stat"><b>02</b><span>Accounting & Payroll</span></div><div className="hero-stat"><b>03</b><span>Business Advisory</span></div></div></section><section id="about" className="intro"><span className="eyebrow">IJ LANGA CONSULTING</span><h2>One place for your business administration.</h2><p>Use the Services menu above to view each service category and its pricing. The Shop will become the purchasing area with SKU-based products, cart, quotes and checkout.</p></section><section id="shop" className="shop-placeholder"><span className="eyebrow">ONLINE SHOP</span><h2>Services ready to purchase</h2><p>Product catalogue, SKU links, cart and quote conversion are next in the build.</p><a className="primary" href="#services">Browse Services <ArrowRight size={18}/></a></section></main><Footer/></> }

createRoot(document.getElementById('root')).render(<App/>);
