import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{FileText,Receipt,ShoppingBag,LogOut,RefreshCw,Download,ArrowLeft,CheckCircle2}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./portal.css';
const money=n=>`R ${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2})}`;
const date=d=>d?new Date(d).toLocaleDateString('en-ZA',{dateStyle:'medium'}):'—';
function Document({type,data,close}){const invoice=type==='invoice';return <div className="portal-modal"><div className="print-sheet"><div className="print-actions"><button onClick={close}>Close</button><button onClick={()=>window.print()}><Download size={15}/> Print / Save PDF</button></div><div className="doc-head"><div><div className="doc-brand">IJ LANGA <span>CONSULTING</span></div><p>Accounting • Taxation • Compliance • Business Consulting</p></div><div className="doc-title"><b>{invoice?'TAX INVOICE':'PAYMENT RECEIPT'}</b><strong>{invoice?data.invoice_number:data.receipt_number}</strong></div></div><div className="doc-meta"><div><b>Customer</b><span>{data.customer?.company_name||data.customer?.contact_name||'Customer'}</span><span>{data.customer?.contact_name||''}</span><span>{data.customer?.email||''}</span></div><div><b>{invoice?'Issue date':'Payment date'}</b><span>{date(invoice?data.issue_date:data.payment_date)}</span><b>Reference</b><span>{data.payment_reference||data.order_number||'—'}</span></div></div>{invoice?<><table className="doc-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>{(data.items||[]).map(i=><tr key={i.id}><td>{i.description}</td><td>{i.quantity}</td><td>{money(i.unit_price)}</td><td>{money(i.total)}</td></tr>)}</tbody></table><div className="doc-totals"><span>Subtotal</span><b>{money(data.subtotal)}</b><span>VAT ({data.vat_rate}%)</span><b>{money(data.vat_amount)}</b><span>Total</span><strong>{money(data.total)}</strong><span>Amount paid</span><b>{money(data.amount_paid)}</b><span>Balance due</span><strong>{money(data.balance_due)}</strong></div></>:<div className="receipt-box"><CheckCircle2 size={32}/><h2>Payment received</h2><p>{money(data.amount)} paid via {data.payment_method||'iKhokha'}.</p><p>Reference: <b>{data.payment_reference||'—'}</b></p></div>}<div className="doc-footer">IJ Langa Consulting (Pty) Ltd · South Africa · Accounting you can trust.</div></div></div>}
function Portal(){const[session,setSession]=useState(null),[customer,setCustomer]=useState(null),[invoices,setInvoices]=useState([]),[receipts,setReceipts]=useState([]),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[document,setDocument]=useState(null);
async function load(s){setSession(s);if(!s){setLoading(false);return}setLoading(true);const{data:c}=await supabase.from('customers').select('*').eq('auth_user_id',s.user.id).maybeSingle();setCustomer(c||null);if(c){const[i,r,o]=await Promise.all([supabase.from('invoices').select('*,invoice_items(*)').eq('customer_id',c.id).order('created_at',{ascending:false}),supabase.from('receipts').select('*').eq('customer_id',c.id).order('payment_date',{ascending:false}),supabase.from('orders').select('*').eq('customer_id',c.id).order('created_at',{ascending:false})]);setInvoices(i.data||[]);setReceipts(r.data||[]);setOrders(o.data||[])}setLoading(false)}
useEffect(()=>{supabase.auth.getSession().then(({data})=>load(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>load(s));return()=>data.subscription.unsubscribe()},[]);
async function sendLink(e){e.preventDefault();setMessage('');const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${window.location.origin}/portal.html`}});setMessage(error?.message||'Check your email for the secure sign-in link.')}
if(loading)return <div className="portal-loading">Loading secure client portal…</div>;
if(!session)return <main className="portal-auth"><div className="portal-auth-card"><div className="portal-eyebrow">IJ LANGA CONSULTING</div><h1>Client Portal</h1><p>Enter your registered email and we will send you a secure sign-in link.</p><form onSubmit={sendLink}><input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><button>Send secure sign-in link</button></form>{message&&<div className="portal-message">{message}</div>}<a href="/">← Return to website</a></div></main>;
const outstanding=invoices.reduce((s,i)=>s+Number(i.balance_due||0),0);return <main className="portal-page"><header className="portal-top"><div><a href="/" className="portal-back"><ArrowLeft size={16}/> Website</a><span className="portal-eyebrow">SECURE CLIENT PORTAL</span><h1>{customer?.contact_name||'Client Portal'}</h1><p>{customer?.company_name||session.user.email}</p></div><div className="portal-actions"><button onClick={()=>load(session)}><RefreshCw size={15}/> Refresh</button><button onClick={()=>supabase.auth.signOut()}><LogOut size={15}/> Sign out</button></div></header><section className="portal-stats"><div><b>{orders.length}</b><span>Orders</span></div><div><b>{invoices.length}</b><span>Invoices</span></div><div><b>{receipts.length}</b><span>Receipts</span></div><div><b>{money(outstanding)}</b><span>Balance due</span></div></section><div className="portal-grid"><section className="portal-card"><div className="portal-card-head"><span className="portal-eyebrow">BILLING</span><h2>Invoices</h2></div>{!invoices.length?<p className="portal-muted">No invoices yet.</p>:invoices.map(i=><div className="portal-row" key={i.id}><div><b>{i.invoice_number}</b><small>{date(i.issue_date)} · {i.status}</small></div><div><strong>{money(i.total)}</strong><span className={Number(i.balance_due)>0?'balance':'paid'}>{Number(i.balance_due)>0?`Due ${money(i.balance_due)}`:'Paid'}</span></div><button onClick={()=>setDocument({type:'invoice',data:{...i,items:i.invoice_items||[],customer}})}><FileText size={15}/></button></div>)}</section><section className="portal-card"><div className="portal-card-head"><span className="portal-eyebrow">PAYMENTS</span><h2>Receipts</h2></div>{!receipts.length?<p className="portal-muted">No receipts yet.</p>:receipts.map(r=><div className="portal-row" key={r.id}><div><b>{r.receipt_number}</b><small>{date(r.payment_date)} · {r.payment_method}</small></div><div><strong>{money(r.amount)}</strong><span className="paid">Successful</span></div><button onClick={()=>setDocument({type:'receipt',data:{...r,customer}})}><Receipt size={15}/></button></div>)}</section><section className="portal-card portal-wide"><div className="portal-card-head"><span className="portal-eyebrow">SERVICE HISTORY</span><h2>Orders</h2></div>{!orders.length?<p className="portal-muted">No orders yet.</p>:orders.map(o=><div className="portal-row" key={o.id}><div><b>{o.order_number}</b><small>{date(o.created_at)} · {o.status}</small></div><div><strong>{money(o.total)}</strong><span className={o.payment_status==='paid'?'paid':'balance'}>{o.payment_status}</span></div><span><ShoppingBag size={16}/></span></div>)}</section></div>{document&&<Document type={document.type} data={document.data} close={()=>setDocument(null)}/>}</main>}
createRoot(document.getElementById('root')).render(<Portal/>);
