import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{supabase}from'./lib/supabase';
import'./quote.css';

const money=n=>`R ${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2})}`;
const readCart=()=>{try{return JSON.parse(localStorage.getItem('ijlanga_cart')||'[]')}catch{return[]}};

function App(){
 const[session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[company,setCompany]=useState(''),[phone,setPhone]=useState(''),[notes,setNotes]=useState(''),[cart,setCart]=useState(readCart),[quotes,setQuotes]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadProfileAndQuotes()},[session]);
 async function loadProfileAndQuotes(){setError('');const{data:p}=await supabase.from('profiles').select('full_name,email').eq('id',session.user.id).maybeSingle();if(p){setFullName(p.full_name||session.user.user_metadata?.full_name||'');setEmail(p.email||session.user.email||'')}else setEmail(session.user.email||'');const{data:q,error:e}=await supabase.from('quotes').select('id,quote_number,customer_name,customer_email,status,subtotal,notes,created_at,quote_items(id,sku,product_name,quantity,unit_price,price_label)').eq('customer_id',session.user.id).order('created_at',{ascending:false});if(e)setError(e.message);else setQuotes(q||[])}
 async function auth(){setBusy(true);setError('');setMessage('');try{if(authMode==='login'){const{error:e}=await supabase.auth.signInWithPassword({email,password});if(e)throw e;setMessage('Signed in successfully.')}else{const{data,error:e}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(e)throw e;if(data.session)setMessage('Account created and signed in.');else setMessage('Account created. Check your email to confirm your account, then sign in.')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submitQuote(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(!cart.length)throw new Error('Your cart is empty. Return to the service catalogue and add a service.');const items=cart.map(i=>({product_id:i.id,quantity:i.qty}));const{data,error:e}=await supabase.rpc('create_quote_from_cart',{p_customer_name:fullName,p_customer_email:email,p_notes:`${company?`Company: ${company}\n`:''}${phone?`Phone: ${phone}\n`:''}${notes}`,p_items:items});if(e)throw e;setMessage(`Quote ${data?.[0]?.quote_number||''} created successfully. Our team will review your request.`);localStorage.removeItem('ijlanga_cart');setCart([]);await loadProfileAndQuotes()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const total=cart.reduce((s,i)=>s+Number(i.price||0)*Number(i.qty||1),0);
 if(!session)return <main className="page"><a className="brand" href="/">IJ LANGA <span>CONSULTING</span></a><section className="card auth"><span className="eyebrow">SECURE CUSTOMER ACCESS</span><h1>{authMode==='login'?'Sign in to request a quote':'Create your customer account'}</h1><p>Use your account to submit and track service quotes.</p>{authMode==='signup'&&<label>Full name<input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<button className="primary" disabled={busy} onClick={auth}>{busy?'Please wait…':authMode==='login'?'Sign In':'Create Account'}</button><button className="link" onClick={()=>{setAuthMode(authMode==='login'?'signup':'login');setError('');setMessage('')}}>{authMode==='login'?'Need an account? Sign up':'Already have an account? Sign in'}</button><a className="back" href="/">← Back to website</a></section></main>;
 return <main className="page"><header className="portal-head"><div><a className="brand" href="/">IJ LANGA <span>CONSULTING</span></a><p>Customer Portal</p></div><button className="link" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><section className="grid"><div className="card"><span className="eyebrow">REQUEST A QUOTE</span><h1>Your services</h1>{cart.length?<><div className="items">{cart.map(i=><div className="item" key={i.sku}><div><b>{i.name}</b><small>{i.sku} · Qty {i.qty}</small></div><strong>{i.priceLabel||money(i.price)}</strong></div>)}</div><div className="total"><span>Estimated subtotal</span><strong>{money(total)}</strong></div></>:<p className="empty">No services are currently in your quote cart. <a href="/">Return to the catalogue.</a></p>}<form onSubmit={submitQuote}><label>Full name<input required value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Company name <span>(optional)</span><input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone <span>(optional)</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Requirements / notes <span>(optional)</span><textarea rows="5" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Tell us anything we should know about your request."/></label>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<button className="primary" disabled={busy||!cart.length}>{busy?'Submitting…':'Submit Quote Request'}</button></form></div><aside className="card"><span className="eyebrow">MY QUOTES</span><h2>Quote history</h2>{quotes.length?<div className="quotes">{quotes.map(q=><article className="quote" key={q.id}><div><b>{q.quote_number}</b><span>{new Date(q.created_at).toLocaleDateString('en-ZA')}</span></div><strong>{money(q.subtotal)}</strong><small>{q.status}</small>{q.quote_items?.length?<ul>{q.quote_items.map(i=><li key={i.id}>{i.product_name} × {i.quantity}</li>)}</ul>:null}</article>)}</div>:<p>No quote requests yet.</p>}<a className="back" href="/">← Browse services</a></aside></section></main>
}
createRoot(document.getElementById('root')).render(<App/>);
