import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{supabase}from'./lib/supabase';
import'./auth-confirm.css';

function App(){const[ready,setReady]=useState(false);const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('Checking your recovery session…');const[error,setError]=useState('');
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data})=>{if(!live)return;if(data.session){setReady(true);setMessage('Choose a new password.')}else setMessage('This reset link is missing or expired. Request a new one.')});const{data}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'&&session){setReady(true);setMessage('Choose a new password.')}});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(password.length<8)throw new Error('Your password must be at least 8 characters.');if(password!==confirm)throw new Error('The passwords do not match.');const{error:e2}=await supabase.auth.updateUser({password});if(e2)throw e2;await supabase.auth.signOut();setReady(false);setMessage('Your password has been updated successfully. You can now sign in.')}catch(e2){setError(e2.message||'Could not update your password.')}finally{setBusy(false)}}
 return <main className="auth-confirm"><section><div className="auth-confirm-icon">🔐</div><span>IJ LANGA CONSULTING</span><h1>Reset password</h1><p>{message}</p>{ready?<form className="reset-form" onSubmit={submit}><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete="new-password"/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required autoComplete="new-password"/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'Updating…':'Change password'}</button></form>:<p><a href="/forgot-password.html">Request a new reset link</a> · <a href="/dashboard.html">Sign in</a></p>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);
